### ISSUE TITLE
[Bug] Collision Arbiter Normals Swapped

### ISSUE THREAD

**Issue by EduardoLopes** [deltaluca/nape#102]
While making my game for [ludum dare 34](http://ludumdare.com/compo/ludum-dare-34/?action=preview&uid=41337), i found a bug, at first i thought it was my code, then i found how to fix it and i guess it is a nape bug.

The api docs says that CollisionArbiter.normal will always point from arbiter's shape1 towards shape2, but doesn't seem to work like this every time, it depends on the order that the shapes are being instantiated.

I made a test. Here's the [source code](https://github.com/EduardoLopes/NapeBug-CollisionArbiter-Normal) and you can see the test running [online](http://eduardolopes.github.io/NapeBug-CollisionArbiter-Normal/). There's some comments in the code explaining what's happening.

Hope this will help figure out what is happening. And if this is not a bug, please help me fix my code, i put a lot of time into this issue trying to fix it without touch nape code.

**Comment by EduardoLopes** [comment]
I fixed this by checking if the id of the shape1 is equal the id of the shape it should be, if not, i swap the normal.

**Comment by alamboley** [comment]
Yeah, I'd the same issue too! Having a crazy one-way platform.

**Comment by alamboley** [comment]
@deltaluca please would you mind to provide a fix & make a release build?

**Comment by alamboley** [comment]
@EduardoLopes just by curiosity, why closing this?

**Comment by EduardoLopes** [comment]
@alamboley I was cleaning up my issue box and this is there since 2016. I don't feel like this will ever be fixed.

**Comment by alamboley** [comment]
@EduardoLopes yup sadly :( thanks for the answer 👍

**Comment by EduardoLopes** [comment]
yea :(

**Comment by alamboley** [comment]
Perhaps it has been fixed there, but can't confirm:
- https://github.com/shirogames/hxnape
- https://github.com/HaxeFlixel/nape-haxe4

**Comment by Gama11** [comment]
nape-haxe4 only fixes compilation with Haxe 4 so far, nothing else. From the commit history I doubt that hxnape does more than that too.

**Comment by MSGhero** [comment]
I think you summoned him from being too busy? https://www.newgrounds.com/bbs/topic/578434/2044#bbspost26513818_post_text
