### ISSUE TITLE
having a central point for objects

### ISSUE THREAD

**Issue by lewislepton** [deltaluca/nape#96]
loving nape, it works great. plus damn easy, so thanks first of all

this is just something ive noticed with say polygon objects, maybe making a rectangle. but once made, then i test hits etc by using a keyboard movement with the keyboard, and hitting another object. but the object im hitting, plus my own player, does not turn naturally. the point where the line is coming from has this type of anchor on it. so when hit/moved, its lined point is much heavier. if that makes sense?

either way, here is a gif to show exactly what i mean. but was wondering how to bypass this?

thanks

![gifgab](https://cloud.githubusercontent.com/assets/11299322/8376884/e75d3f5c-1c03-11e5-9c35-4fb51f15c65b.gif)

**Comment by lewislepton** [comment]
its really so the shape can have a more central affected area, rather than a corner, which is not realistic

thanks

**Comment by deltaluca** [comment]
the image just shows up as a grey quad for me?

**Comment by lewislepton** [comment]
oh really. i thought it was animating the gif. its not very clear. ill post another see if that works. anyhow, here is a new one

![image](https://cloud.githubusercontent.com/assets/11299322/8397993/974761d4-1dd7-11e5-9877-c6e394504fa0.gif)

if that doesnt work, here are 2 images to hopefully make sense with some words ;)
but in this first image im pushing down, BUT, the corner has this type of anchor on. but...
![screen shot 2015-06-28 at 20 52 01](https://cloud.githubusercontent.com/assets/11299322/8398001/c5640c48-1dd7-11e5-99a8-5abc1bcfa19c.png)

when i push on the other corner that does not have the line, it pushes down a hell of a lot easier
![screen shot 2015-06-28 at 20 52 10](https://cloud.githubusercontent.com/assets/11299322/8398006/d87003d2-1dd7-11e5-9d53-10178dddf042.png)

so the big block has this type of anchor in the corner where the line goes to/from

hope that helps to explain ;)

**Comment by deltaluca** [comment]
The line (assuming this is the inbuilt debug drawing) is just going from the centre of the polygon to its first vertex, it's not an anchor.

Without seeing any code, the only thing I can suggest is happening is that you've not created the polygon such that it's centre of mass is at (0, 0) and as such it will not behave realistically (eg you've created it with Polygon.rect(0, 0, w, h) rather than Polygon.box(w, h) == Polygon.rect(-w/2,-h/2,w,h))

**Comment by lewislepton** [comment]
AH, ```box``` - that was the key. silly me indeed

many thanks for the help ;)
